server:
  port: 8080

spring:
  application:
    name: oop-project
  datasource:
    url: jdbc:postgresql://localhost:5432/oop_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
