spring:
  application:
    name: oop-project
  profiles:
    active: local # 기본값으로 local 실행

server:
  port: 8080

jwt:
  secret: oop-project-jwt-secret-key-must-be-at-least-256-bits-long-here
  expiration: 1800000 # 30분 (ms)
  refresh-expiration: 604800000 # 7일 (ms)

filter:
  url-patterns:
    - /posts/*
    - /posts
    - /users/*
    - /users
